# Elastic Beanstalk에 배포하기위해 CodeBulid를 이용하여 Typescript를 Javascrip로 트랜스파일
version: 0.2

phases:
  install:
    #Ubuntu 표준 이미지 2.0 이상을 사용하는 경우 런타임 버전을 지정해야 합니다.
    #런타임 버전을 지정하는 경우 Ubuntu 표준 이미지 2.0 이외의 이미지를 사용하면 빌드에 실패합니다.
    runtime-versions:
      nodejs: 14
    commands:
      - n 16
      - npm i
  pre_build:
    commands:
    # - cp -r ./src/public ./
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - ls -al
artifacts:
  files:
    - 'package*.json'
    - 'dist/**/*'
    - 'node_modules/**/*'
