export const colMapper = {
  contentColActive: 'content_name',
  trialColActive: 'trialid_name',
  probtableColActive: 'probtable_name',
  trialresultColActive: 'trialresult_name',
  countColActive: 'count',
  probColActive: 'prob',
  realProbColActive: 'realprob',
  content_name: 'contentColActive',
  trialid_name: 'trialColActive',
  probtable_name: 'probtableColActive',
  trialresult_name: 'trialresultColActive',
  count: 'countColActive',
  prob: 'probColActive',
  realprob: 'realProbColActive',
};
